# 1.

In [17]:
from Vector import *

ModuleNotFoundError: No module named 'Vector'

# 2.

In [83]:
a=VectorPolar(3,np.pi,2*np.pi)
b=VectorPolar(1,np.pi,2*np.pi)
a.magnitud #Probamos magnitud.

3.0

In [81]:
a.Esf_to_cart() #Probamos transformación.

[3.6739403974420594e-16, -8.998558695971146e-32, -3.0]


# 3.

In [49]:
a=VectorCartesiano(1.5,0,2.4)
b=VectorCartesiano(0,1,9)
c=VectorCartesiano(4.2,0.05,0)

In [50]:
a.Cart_to_esf() #Transformamos a esféricas *a*.

[2.8301943396169813, 0.5585993153435626, 0.0]


In [51]:
b.Cart_to_esf() #Transformamos a esféricas *b*.

[9.055385138137417, 0.11065722117389662, 1.5707963267948966]


In [52]:
c.Cart_to_esf() #Transformamos a esféricas *c*.

[4.200297608503474, 1.5707963267948966, 0.011904199558309828]


In [53]:
a*b #Producto punto a y b.


21.599999999999998

In [54]:
a*c #Producto punto a y c.

6.300000000000001

In [55]:
b*c #Producto punto b y c.

0.05

In [56]:
a.Cruz(0,1,9) #Producto cruz a y b.

array([ -2.4, -13.5,   1.5])

In [57]:
a.Cruz(4.2,0.05,0) #Producto cruz a y c.

array([-0.12 , 10.08 ,  0.075])

In [58]:
b.Cruz(4.2,0.05,0) #Producto cruz b y c.

array([-0.45, 37.8 , -4.2 ])

In [62]:
ang_ab=(a*b)/(a.magnitud*b.magnitud) #Ángulo entre a y b.
ang_ac=(a*c)/(a.magnitud*c.magnitud) #Ángulo entre a y c.
ang_bc=(b*c)/(b.magnitud*c.magnitud) #Ángulo entre b y c.

print("El ángulo entre a y b es: %f, El ángulo entre a y c es: %f, El ángulo entre b y c es: %f."%(ang_ab,ang_ac,ang_bc))

El ángulo entre a y b es: 0.842812, El ángulo entre a y c es: 0.529961, El ángulo entre b y c es: 0.001315.
